Repository unit-team-spbu/backend, pull requests merged in 2020-10, with the labels that each got.

#19 Issues/18
  crawler/softline_crawler/Dockerfile
  crawler/softline_crawler/README.md
  crawler/softline_crawler/config.yml
  crawler/softline_crawler/docker-compose.yml
  crawler/softline_crawler/requirements.lock
  crawler/softline_crawler/requirements.txt
  crawler/softline_crawler/run.sh
  crawler/softline_crawler/softline_crawler.py
Labels: groundwork

#22 Issues/21
  crawler/it_world_crawler/Dockerfile
  crawler/it_world_crawler/README.md
  crawler/it_world_crawler/config.yml
  crawler/it_world_crawler/docker-compose.yml
  crawler/it_world_crawler/it_world_crawler.py
  crawler/it_world_crawler/requirements.lock
  crawler/it_world_crawler/requirements.txt
  crawler/it_world_crawler/run.sh
  docker-compose.yml
Labels: challenge, groundwork, on-review, wip

#24 issues/23 add none check
  crawler/it_events_crawler/it_events_crawler.py
  crawler/it_world_crawler/it_world_crawler.py
  das/event_das/event_das.py
  preh/preh.py
  rec/rec.py
Labels: bug

#30 Issues/26
  auth/Dockerfile
  auth/README.md
  auth/auth.py
  auth/config.py
  auth/config.yml
  auth/docker-compose.yml
  auth/requirements.txt
  auth/run.sh
  docker-compose.yml
Labels: groundwork

#33 Issues/27
  gateway/Dockerfile
  gateway/README.md
  gateway/config.yml
  gateway/gateway.py
  gateway/requirements.txt
  gateway/run.sh
Labels: groundwork, wip

#32 Issues/29
  uis/Dockerfile
  uis/README.md
  uis/config.yml
  uis/docker-compose.yml
  uis/requirements.txt
  uis/run.sh
  uis/uis.py
Labels: blocked, experimental, groundwork, wip

#35 Issues/34
  das/top_das/Dockerfile
  das/top_das/README.md
  das/top_das/config.yml
  das/top_das/docker-compose.yml
  das/top_das/requirements.txt
  das/top_das/run.sh
  das/top_das/top_das.py
Labels: groundwork

#38 Issues/36
  filter/Dockerfile
  filter/README.md
  filter/config.yml
  filter/filter.py
  filter/requirements.txt
  filter/run.sh
Labels: groundwork

#40 Issues/37
  ranking/Dockerfile
  ranking/README.md
  ranking/config.yml
  ranking/docker-compose.yml
  ranking/ranking_service.py
  ranking/requirements.txt
  ranking/run.sh
Labels: groundwork, question, wip

#44 issues/41 and 42
  das/event_das/event_das.py
Labels: groundwork
