Repository unit-team-spbu/backend, pull requests merged in 2020-11, with the labels that each got.

#48 issues/47 add mocked gateway service
  mocked gateway/Dockerfile
  mocked gateway/config.yml
  mocked gateway/docker-compose.yml
  mocked gateway/gateway.py
  mocked gateway/requirements.txt
  mocked gateway/run.sh
Labels: experimental, groundwork

#57 Issues/52
  das/event_das/event_das.py
  das/top_das/top_das.py
Labels: groundwork

#59 Issues/56
  reaction/likes/Dockerfile
  reaction/likes/README.md
  reaction/likes/config.yml
  reaction/likes/docker-compose.yml
  reaction/likes/likes.py
  reaction/likes/requirements.txt
  reaction/likes/run.sh
  uis/uis.py
Labels: groundwork, wip

#60 Issues/58
  reaction/favorites/Dockerfile
  reaction/favorites/README.md
  reaction/favorites/config.yml
  reaction/favorites/docker-compose.yml
  reaction/favorites/favorites.py
  reaction/favorites/requirements.txt
  reaction/favorites/run.sh
  uis/uis.py
Labels: groundwork, wip

#69 issues/67 add tests with readme
  tests/1.collector.rest
  tests/2.auth.rest
  tests/3.interests.rest
  tests/4.feed.rest
  tests/5.unauth.rest
  tests/6.reactions.rest
  tests/7.update.rest
  tests/README.md
Labels: experimental, groundwork
